services:
  - type: web
    name: isecure-crm
    env: python
    buildCommand: "python manage.py collectstatic --noinput"
    startCommand: "gunicorn crmproject.wsgi:application"
    staticPublishPath: staticfiles
    envVars:
      - key: USE_POSTGRES
        value: "True"
      - key: DATABASE_URL
        value: postgresql://crm_db_0ndg_user:gkNhdiZFHxhjQYuCW3keOI35An8dXRev@dpg-d3g25eb3fgac73c3mrug-a/crm_db_0ndg_3v5b
      - key: SECRET_KEY
        value: "dy)#&kpi*)tgy=#%qu23ip7_xxk9)plw0fh7ltsv=31=u98lv!"  # Replace with your actual key
      - key: ALLOWED_HOSTS
        value: "www.crm.isecuresolutions.in,crm.isecuresolutions.in,.cfargotunnel.com,.onrender.com"
      - key: SITE_URL
        value: "https://crm.isecuresolutions.in"
      - key: USE_POSTGRES
        value: "False"  # Set to "True" if you're using PostgreSQL
